
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Guillaume Charest
description: >-
    Ce blog contient des informations recueillies auprès de sources variées ainsi que des observations. Sujets principaux: programmation, logiciels libres, diabète.
index:
  en:
  fr: index.html
language:
  en: English
  fr: Français
home:
  en: Home
  fr: Accueil
home_link:
  en:
  fr: index.html
about:
  en: About
  fr: À propos
about_link:
  en: about.html
  fr: apropos.html
baseurl: "/blog"
url: "https://gcharest.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: GuillCharest
github_username:  gcharest

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
